name: pqc_interop
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.0
  path: ^1.8.3
  # path: ^1.8.0

dev_dependencies:
  ffi: ^2.1.0
  ffigen: ^11.0.0
  lints: ^3.0.0
  test: ^1.21.0
